---
version: 1
build_arg_defaults:
  ANSIBLE_RUNNER_IMAGE: 'quay.io/ansible/ansible-runner:stable-2.11-devel'
  PYTHON_BUILDER_IMAGE: 'quay.io/ansible/python-builder:latest'
ansible_config: 'ansible.cfg'
dependencies:
  galaxy: _build/requirements.yml
  system: _build/bindep.txt
  python: _build/requirements.txt
additional_build_steps:
  prepend:
    - RUN whoami
  append:
    - RUN alternatives --set python /usr/bin/python3
    - COPY --from=quay.io/project-receptor/receptor:0.9.7 /usr/bin/receptor /usr/bin/receptor
    - RUN mkdir -p /var/run/receptor
    - ADD run.sh /run.sh
    - CMD /run.sh
    - USER 1000
    - RUN git lfs install
